Fixes #559: No newline in EMAIL_SUBJECT_PREFIX.
tl-its-umich-edu/remote-office-hours-queue pull request #587
Opened 2024-12-06 16:22 UTC by jadfalaoui

Added an extra assert statement to ensure EMAIL_SUBJECT_PREFIX doesn't contain a newline character. I made sure to stay consistent with the existing tests for redis_host as mentioned in #473.

2024-12-06 17:03 UTC, jonespm commented
Thanks @jadfalaoui. This looks like it just fixes the test for the issue but the issue isn't fixed. If the EMAIL_SUBJECT_PREFIX contains new lines this test will fail. 

So this should also be fixed in https://github.com/tl-its-umich-edu/remote-office-hours-queue/blob/master/src/officehours/settings.py to prevent this from ever being an issue regardless if it has newlines or not.

2024-12-06 17:03 UTC, jonespm requested changes
Requested changes as this just fixes the test, not the code.

2024-12-06 17:09 UTC, jadfalaoui commented
Hi @jonespm, thank you for bringing it to my attention. I added it to the settings.py file to prevent this from being an issue.

2024-12-06 17:25 UTC, jonespm approved these changes
Okay this seems good, thanks for the contribution!

2024-12-06 17:26 UTC, merged

2024-12-06 17:31 UTC, jadfalaoui commented
Thank you for the quick feedback!

2024-12-09 03:05 UTC, zqian commented
@jadfalaoui I got the following error with `docker compose up`, after this PR merge:

"remote-office-hours-queue-web-1              |   File "/usr/src/app/officehours/settings.py", line 299, in <module>
remote-office-hours-queue-web-1              |     EMAIL_HOST = os.getenv('EMAIL_HOST').strip()
remote-office-hours-queue-web-1              | AttributeError: 'NoneType' object has no attribute 'strip'"

Neither `EMAIL_HOST` or `EMAIL_SUBJECT_PREFIX` is defined as environment variable inside the docker-compose.yaml file. 

Could you please fix the above error?

2024-12-09 19:31 UTC, hanzheg commented
Got the same error with zqian